
package it.beije.rubrica.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContactsImplService", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", wsdlLocation = "http://localhost:9000/contacts?wsdl")
public class ContactsImplService
    extends Service
{

    private final static URL CONTACTSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTACTSIMPLSERVICE_EXCEPTION;
    private final static QName CONTACTSIMPLSERVICE_QNAME = new QName("http://server.contacts.jaxws.ws.beije.it/", "ContactsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/contacts?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTACTSIMPLSERVICE_WSDL_LOCATION = url;
        CONTACTSIMPLSERVICE_EXCEPTION = e;
    }

    public ContactsImplService() {
        super(__getWsdlLocation(), CONTACTSIMPLSERVICE_QNAME);
    }

    public ContactsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTACTSIMPLSERVICE_QNAME, features);
    }

    public ContactsImplService(URL wsdlLocation) {
        super(wsdlLocation, CONTACTSIMPLSERVICE_QNAME);
    }

    public ContactsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTACTSIMPLSERVICE_QNAME, features);
    }

    public ContactsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContactsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Contacts
     */
    @WebEndpoint(name = "ContactsImplPort")
    public Contacts getContactsImplPort() {
        return super.getPort(new QName("http://server.contacts.jaxws.ws.beije.it/", "ContactsImplPort"), Contacts.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Contacts
     */
    @WebEndpoint(name = "ContactsImplPort")
    public Contacts getContactsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.contacts.jaxws.ws.beije.it/", "ContactsImplPort"), Contacts.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTACTSIMPLSERVICE_EXCEPTION!= null) {
            throw CONTACTSIMPLSERVICE_EXCEPTION;
        }
        return CONTACTSIMPLSERVICE_WSDL_LOCATION;
    }

}
