
package it.beije.rubrica.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Contacts", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Contacts {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addContact", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.rubrica.webservice.AddContact")
    @ResponseWrapper(localName = "addContactResponse", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.rubrica.webservice.AddContactResponse")
    @Action(input = "http://server.contacts.jaxws.ws.beije.it/Contacts/addContactRequest", output = "http://server.contacts.jaxws.ws.beije.it/Contacts/addContactResponse")
    public boolean addContact(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNames", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.rubrica.webservice.GetNames")
    @ResponseWrapper(localName = "getNamesResponse", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.rubrica.webservice.GetNamesResponse")
    @Action(input = "http://server.contacts.jaxws.ws.beije.it/Contacts/getNamesRequest", output = "http://server.contacts.jaxws.ws.beije.it/Contacts/getNamesResponse")
    public List<String> getNames();

    /**
     * 
     * @return
     *     returns java.util.List<it.beije.rubrica.webservice.Contact>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContacts", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.rubrica.webservice.GetContacts")
    @ResponseWrapper(localName = "getContactsResponse", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.rubrica.webservice.GetContactsResponse")
    @Action(input = "http://server.contacts.jaxws.ws.beije.it/Contacts/getContactsRequest", output = "http://server.contacts.jaxws.ws.beije.it/Contacts/getContactsResponse")
    public List<Contact> getContacts();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<it.beije.rubrica.webservice.Contact>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContactByParameter", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.rubrica.webservice.GetContactByParameter")
    @ResponseWrapper(localName = "getContactByParameterResponse", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.rubrica.webservice.GetContactByParameterResponse")
    @Action(input = "http://server.contacts.jaxws.ws.beije.it/Contacts/getContactByParameterRequest", output = "http://server.contacts.jaxws.ws.beije.it/Contacts/getContactByParameterResponse")
    public List<Contact> getContactByParameter(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<it.beije.rubrica.webservice.Contact>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContactsByName", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.rubrica.webservice.GetContactsByName")
    @ResponseWrapper(localName = "getContactsByNameResponse", targetNamespace = "http://server.contacts.jaxws.ws.beije.it/", className = "it.beije.rubrica.webservice.GetContactsByNameResponse")
    @Action(input = "http://server.contacts.jaxws.ws.beije.it/Contacts/getContactsByNameRequest", output = "http://server.contacts.jaxws.ws.beije.it/Contacts/getContactsByNameResponse")
    public List<Contact> getContactsByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
